### ISSUE TITLE
Funktioniert nicht

### ISSUE THREAD

**Issue by justinb1617** [HimmelKreis4865/expressphp#1]
```php
public function start () {
        self::$app = new App();
        ($app = self::$app)->listen(80, "0.0.0.0", function () {
            BackendServer::log("Started.");
        });
        $app->get("/", function (Request $request, Response $response) {
            $response->code(200);
            $response->body(["info" => "rest-api is working"]);
        });
        $app->default(function (Request $request, Response $response) {
            $response->body(["error" => "INVALID " . $request->data()->path()]);
        });
    }
```

![image](https://user-images.githubusercontent.com/57451491/213511480-085eccee-4a6e-4f29-8e21-d8fbc8f08bc8.png)
![image](https://user-images.githubusercontent.com/57451491/213511601-59428612-88ca-43ac-94b1-ab01d5c49f8c.png)
![image](https://user-images.githubusercontent.com/57451491/213511662-df538d71-65c9-4991-b42b-bf10491d9744.png)

**Comment by HimmelKreis4865** [comment]
expressphp ist so designed, dass es als eigenständiges programm läuft - `App->listen()` startet die app und startet eine blockende loop, nichts danach wird ausgeführt

**Comment by justinb1617** [comment]
also alles davor?

**Comment by justinb1617** [comment]
geht jetzt, danke :D
